# Generated by Django 3.1.7 on 2021-04-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Superhero',
        ),
    ]
