# Generated by Django 3.1.7 on 2021-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_auto_20210406_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
